pipeline {
  agent any
    
  tools {nodejs "node"}
    
  stages { 
    stage('Cloning Git') {
      steps {
        git 'https://github.com/anderslatif/dev_env_2019'
      }
    }
        
    stage('Install dependencies') {
      steps {
        sh 'npm install --prefix ./devenv__project'
      }
    }
     
    stage('Test login') {
      steps {
         sh 'CI=true npm test login.spec.js --prefix ./devenv__project -- -u'
      }
    }

    stage('Test admin') {
      steps {
         sh 'CI=true npm test admin.spec.js --prefix ./devenv__project -- -u'
         
      }
    }      
  }
}
