pipeline {
  agent any
    
  tools {nodejs "node"}
    
  stages {
        
    stage('Cloning Git') {
      steps {
        git 'https://github.com/anderslatif/dev_env_2019'
      }
    }
        
    stage('Install dependencies') {
      steps {
        sh 'npm install --prefix ./devenv__project'
      }
    }
     
    stage('Test') {
      steps {
         sh 'npm test --prefix ./devenv__project'
      }
    }      
  }
}
