pipeline {
  agent any
    
  tools {nodejs "node"}
    
  stages { 
    stage('Cloning Git') {
      steps {
        git 'https://github.com/anderslatif/dev_env_2019'
      }
    }
        
    stage('Install dependencies') {
      steps {
        sh 'npm install --prefix ./devenv__project --production'
        sh 'npm install --prefix ./devenv__project/backend --production'
      }
    }
     
    stage('Tests') {
      steps {
         sh 'CI=true npm test --prefix ./devenv__project -- -u'
      }
    }
    stage('Build') {
      steps {
         sh 'npm run-script build --prefix ./devenv__project'
      }
    }
    stage('Deploy') {
      steps {
         sh './devenv__project/deploy.sh'
      }
    }
  }
}
